# .github/workflows/auto-update.yml
name: Auto-Update CO-Cloud Threat Journal & Blacklist

on:
  schedule:
    - cron: '0 05 * * *'    # daily at 05:00 UTC
  workflow_dispatch:

jobs:
  update-threat-journal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Celestial Ocean Cloud repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install scan script dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests pyyaml

      - name: Run HannahAI™ mimic scan & write Threat Journal
        run: |
          chmod +x scripts/scan-hannah-mimics.py
          python3 scripts/scan-hannah-mimics.py \
            > threat_journal.yaml

      - name: Extract blacklist entries
        run: |
          python3 scripts/scan-hannah-mimics.py \
            | awk '/^    "https?:\/\// { gsub(/[,"]/, ""); print }' \
            > config/blacklist_repos.txt

      - name: Commit & push updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: chore: auto-update threat journal & blacklist
          author_name: Celestial Bot
          author_email: ci@celestial-ocean.local
          file_pattern: |
            threat_journal.yaml
            config/blacklist_repos.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}