name: Weekly Mimic Scan – Celestial Ocean Coding™

on:
  schedule:
    - cron: '0 5 * * 1'    # Every Monday 05:00 UTC
  workflow_dispatch:

jobs:
  ocean-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./co-cloud

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        working-directory: ./co-cloud/scripts
        run: pip install requests pyyaml

      - name: Run Mimic Scan
        working-directory: ./co-cloud/scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x scan-hannah-mimics.py
          ./scan-hannah-mimics.py \
            | tee ../../threat_journal.yaml
          # Append new blacklisted repos into the CO Cloud filter
          ./scan-hannah-mimics.py | awk '/http/ { print }' \
            > ../../config/blacklist_repos.txt