name: Sentinel CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sentinel-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with Pytest
      run: |
        pytest

    - name: Ping FastAPI Health Endpoint
      run: |
        curl --fail http://localhost:8000/health/env || exit 1
      continue-on-error: true
